### ISSUE TITLE
Some Botania recipes are missing textures in JEI

### ISSUE THREAD

**Issue by KodiakJak** [Soartex-Modded/Modded-1.10.x#30]
Some Botania recipes are missing textures in JEI such as Dreamwood and Metamorphic items.

Screenshot - ![Screenshot](http://i.imgur.com/fvzEJn6.png)

**Comment by artdude543** [comment]
This is due to a bug with the models. The textures are there but we need to make changes. This will take sometime as it requires an entire re-write for the model files and textures.

**Comment by Shoeboxam** [comment]
I have rewritten the model files in vanilla Fanver and Invictus. The rewrite should fix this issue. I do not have the time to check, but the rewritten model files will become available soon and you will be able to verify that this issue has been fixed.

**Comment by Shoeboxam** [comment]
Fanver vanilla has been updated with my model structure rewrite. I have confirmed that the model rewrite fixes the Botania render issues. Be sure to use Fanver 4.0.1 as your resource pack base! Invictus models have also been restructured to be compatible.

**Comment by zISKo666** [comment]
Ok, does this update work with 1.10.2 also?

**Comment by Shoeboxam** [comment]
Sure does! Let me know if you see any problems. It might warn that the pack was made for a newer version of minecraft, I can't remember if they bumped the pack version or not. But they should be interchangeable.

**Comment by zISKo666** [comment]
This is what i get with version 4.0.1 and i have no clue how to solve it.

![2017-01-23_20 40 23](https://cloud.githubusercontent.com/assets/6992216/22219782/71503876-e1ac-11e6-845f-a1c9f283cfb2.png)
![2017-01-23_20 40 42](https://cloud.githubusercontent.com/assets/6992216/22219783/715611b0-e1ac-11e6-811a-d55274cf91a4.png)

**Comment by Shoeboxam** [comment]
That's interesting! I'll debug it when I get the chance.

**Comment by artdude543** [comment]
You'd have to remove the "vanilla" textures from the universal before adding the fixed Fanver on top as you just create the same issue. Also the Universal is not shipping with the latest fixes. That still needs updating and back porting for how the script works. I'll do that sometime tonight if I get the chance.

**Comment by Shoeboxam** [comment]
I don't get any errors when I test the 4.0.1 pack with mod patches in 1.10.2. 

In 4.0.1, if a vanilla block is modified in any way, then all children are re-implemented (no dependencies on inherited files, and no vanilla files are modified).

Here's a Botania model for one of the wall elements. Notice the reference to minecraft:block/wall_side.
`{  
  "parent": "minecraft:block/wall_side",  
  "textures": {  
    "wall": "botania:blocks/biomeStone14"  
  }  
}`  

I had modified minecraft:block/wall_side in vanilla to take one texture for the side and one for the top:  
`{  
    "textures": {  
        "particle": "#side"  
    },  
    "elements": [  
        {   "from": [ 5, 0, 0 ],  
            "to": [ 11, 13, 8 ],  
            "faces": {  
                "down":  { "texture": "#normal", "cullface": "down" },  
                "up":    { "texture": "#top" },  
                "north": { "texture": "#side", "cullface": "north" },  
                "west":  { "texture": "#side" },  
                "east":  { "texture": "#side" }  
            },  
            "__comment": "wall"  
        }  
    ]  
}`  
Notice the references to #normal and #top when Botania is only supplying #wall.  

In 4.0.1, the Soartex vanilla walls inherit from minecraft:block/wall/side instead. Thus the vanilla implementation that expects a #wall texture parameter is left untouched, and the blockstates for vanilla walls are adjusted to point toward alternative model files. If the old modified minecraft:block/wall_side is still out there somewhere in your resource pack stack, then it will bust all its children in mods.

I did notice the default door textures are loaded in your screenshot, so I suspect that you have already removed the old version of Fanver. This would mean the conflicts come from somewhere else. I can't know for sure yet.

Could you pastebin your console log? I know it's probably huge, but it would make a big difference, considering that I'm having problems reproducing this one.

Another question, do the errant blocks in JEI render correctly in-world and in-hand?



SIDE NOTE: You can give custom textures to mod stairs, walls, slabs, anything, by modifying the parent and supplying new texture parameters:
`{  
  "parent": "minecraft:block/wall/side",  
  "textures": {  
    "normal": "botania:blocks/biomeStone14_wall_side",
    "top":      "botania:blocks/biomeStone14_wall_top"
  }  
}`

EDIT: Hey. I just got the error. I'm messing with it.

**Comment by zISKo666** [comment]
I'll look into this at the weekend.

**Comment by Shoeboxam** [comment]
So I've fixed three bugs related to this issue now.
1. Rewritten models to fix dependencies (4.0.1)
2. Outdated mana pool aspect ratio  4eaf706
3. Errant file signatures hiding .jpeg files  3983304 

The textures on the repo should work now, with these changes. The mod patch won't be updated until the script runs in the next day or so.

**Comment by zISKo666** [comment]
Sorry for my late answer (busy weekend).

With the changes you made it is looking good so far. Thank you :)
Excepting the biomestone1.png (red) it do not fit the other blocks (green).

The last problem I have are these walls (yellow). I do not understand how to fix them.
Can you tell me which file(s) I have to change?

![2017-01-30_17 35 31](https://cloud.githubusercontent.com/assets/6992216/22432375/02b49560-e715-11e6-9e7f-e57b02ed194d.png)

Edit: In the log file I found a lot of ...

[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_post
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/fence_post
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/fence_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_post
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in minecraft:models/block/wall_side
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #particle in minecraft:models/block/door_top_rh
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #frame in minecraft:models/block/door_top_rh
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #frame in minecraft:models/block/door_top_rh
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #frame in minecraft:models/block/door_top_rh
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #frame in minecraft:models/block/door_top_rh
[17:17:55] [Client thread/WARN]: Unable to resolve texture due to upward reference: #texture in minecraft:models/block/door_top_rh

**Comment by Shoeboxam** [comment]
Is this still an issue in the latest universal pack?

**Comment by alfw** [comment]
As of [this build ](https://minecraft.curseforge.com/projects/soartex-fanver-modded/files/2383494) and  Botania r1.9-340 there are no missing texures in JEI / NEI.

**Comment by zISKo666** [comment]
just FYI

Tested the latest release and it is working fine.
The only things still broken are the vanilla doors because of the mod malisisdoors.
They are working fine with the old 1.7.10 way.

I think i found a solution for this problem.
Malisis Doors uses own textures for the vanilla doors.
So i just have to copy them to the malisi doors texture folder and it should be fine :)

**Comment by artdude543** [comment]
Malisis Doors will require us to supply custom model fixes. They do a lot of hacking to default MC models >.>

**Comment by Shoeboxam** [comment]
@zISKo666: The issue with Malisis doors was resolved with Malisis doors 6.1.0.

**Comment by zISKo666** [comment]
@Shoeboxam Unfortunately that version is for 1.11.2 only and afaik there is no backport to 1.10.2 (5.2.0) atm. Even texturing Malisis Doors on its own is not working well.

Similar to that issue: https://github.com/Ordinastie/MalisisDoors/issues/133
